### ISSUE TITLE
Parallelism

### ISSUE THREAD

**Issue by jb55** [damus-io/noteguard#1]
Someone mentioned that it would be nice if the pipeline ran in parallel. Maybe this could be a configurable option?

```toml
parallel = true
pipeline = ["ratelimit", "push_notifications"]
```

In this mode, each filter could be ran in parallel. For most filters this would likely just make things slower, but if there are lots of filters that individually take some time it might make sense? 

On the first reject result it could return that, while cancelling the other threads.
